#!/bin/bash
# chkconfig: 2345 20 80
# processname: slashproc_parsers
# description: Launches simple json-rpc /proc parsing localhost server

DAEMON_NAME=slashproc_parsers
DAEMON_USER=root
BIN="/usr/bin/python"
ARGS="-m slashproc_parser.basic_server"
PIDFILE="/var/run/$DAEMON_NAME.pid"

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting daemon $DAEMON_NAME"
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $BIN -- $ARGS
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping daemon $DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 