#!/bin/bash
# chkconfig: 2345 20 80
# description: Launches simple json-rpc /proc parsing localhost server

LAUNCH_COMMAND="python -m slashproc_parser.basic_server"

start() {
    $LAUNCH_COMMAND &
}

stop() {
    kill $(ps aux | grep "$LAUNCH_COMMAND" | awk '{print $2}')
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 