#!/bin/bash

# chkconfig: 2345 20 80
# description: Launches simple json-rpc /proc parsing localhost server

### BEGIN INIT INFO
# Provides:          slashproc-parsers
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      2 3 4 5
# Short-Description: Starts slashproc_parsers localhost server
# Description:       Starts basic HTTP-server from slashproc_parsers python module
#     that provides parsers for /proc catalogue files
### END INIT INFO

NAME=slashproc-parsers
DAEMON=slashproc-parsers
DAEMON_BIN=/usr/bin/python
DAEMON_ARGS="-m slashproc_parser.basic_server"
PIDFILE=/var/run/$NAME.pid

start() {
    printf "%-50s" "Starting $NAME..."
    PID=`$DAEMON_BIN $DAEMON_ARGS > /dev/null 2>&1 & echo $!`
    if [ -z $PID ]; then
        printf "Fail\n"
    else
        echo $PID > $PIDFILE
        printf "OK\n"
    fi
}

status() {
    printf "%-50s" "Check $NAME status..."
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        if [ -z "`ps axf | grep ${PID} | grep -v grep`"]; then
            printf "Process dead but PID-file exists\n"
        else
            echo "Running..."
        fi
    else
        printf "Service not running\n"
    fi
}

stop() {
    printf "%-50s" "Stopping $NAME..."
    PID=`cat $PIDFILE`
    if [ -f $PIDFILE ]; then
        kill -HUP $PID
        printf "OK\n"
        rm -f $PIDFILE
    else
        printf "PID-file not found\n"
    fi
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
